[project]
name = "dbs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "discord-py>=2.5.2",
    "matplotlib>=3.10.3",
    "requests>=2.32.4",
]
